services:
  _defaults:
    public: true

  cdigruttola.packageweight.module:
    class: Packageweight
    factory: [ 'Module', 'getInstanceByName' ]
    public: false
    arguments:
      - 'packageweight'

  cdigruttola.module.packageweight.repository.package_weight:
    class: cdigruttola\Module\PackageWeight\Repository\PackageRangeWeightRepository
    public: true
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - cdigruttola\Module\PackageWeight\Entity\PackageRangeWeight
